// Package aiagent defines the internal Memos-to-AI Service delegation boundary.
package aiagent

import (
	"crypto/hmac"
	"crypto/sha256"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"
)

const (
	// InternalAnswerPath is reserved for Memos-authenticated Agent delegation.
	InternalAnswerPath = "/internal/ai/agent/answer"

	// Header names remain private to the Memos-to-AI Service boundary.
	SignatureHeader = "X-DevMemo-Agent-Signature"
	TimestampHeader = "X-DevMemo-Agent-Timestamp"

	signaturePrefix  = "sha256="
	signatureVersion = "devmemo-agent-v1"
)

// DelegatedAnswerRequest contains no identity or raw Memo content. Memos derives
// the visible Memo UID capability from its authenticated request context.
type DelegatedAnswerRequest struct {
	Question        string   `json:"question"`
	Limit           int      `json:"limit"`
	VisibleMemoUIDs []string `json:"visible_memo_uids"`
}

// Validate checks the small, fixed internal request contract.
func (r DelegatedAnswerRequest) Validate() error {
	if strings.TrimSpace(r.Question) == "" {
		return errors.New("question must not be empty")
	}
	if r.Limit < 1 || r.Limit > 10 {
		return errors.New("limit must be between 1 and 10")
	}

	seen := make(map[string]struct{}, len(r.VisibleMemoUIDs))
	for _, uid := range r.VisibleMemoUIDs {
		normalizedUID := strings.TrimSpace(uid)
		if normalizedUID == "" {
			return errors.New("visible_memo_uids must not contain empty values")
		}
		if _, exists := seen[normalizedUID]; exists {
			return errors.New("visible_memo_uids must not contain duplicates")
		}
		seen[normalizedUID] = struct{}{}
	}
	return nil
}

// SignedHeaders are generated by Memos and verified by AI Service before any
// retrieval or context assembly occurs.
type SignedHeaders struct {
	Signature string
	Timestamp string
}

// SignRequest signs one raw request body and the request method/path binding.
func SignRequest(method, path string, body []byte, at time.Time, secret string) (SignedHeaders, error) {
	if strings.TrimSpace(secret) == "" {
		return SignedHeaders{}, errors.New("agent internal signing secret must not be empty")
	}
	if strings.TrimSpace(method) == "" || strings.TrimSpace(path) == "" {
		return SignedHeaders{}, errors.New("method and path must not be empty")
	}

	timestamp := strconv.FormatInt(at.UTC().Unix(), 10)
	mac := hmac.New(sha256.New, []byte(secret))
	_, _ = mac.Write(canonicalRequest(method, path, timestamp, body))
	return SignedHeaders{
		Signature: signaturePrefix + fmt.Sprintf("%x", mac.Sum(nil)),
		Timestamp: timestamp,
	}, nil
}

// VerifyRequest validates the signature and bounded timestamp without
// differentiating malformed and mismatched signatures to a caller.
func VerifyRequest(method, path string, body []byte, headers SignedHeaders, now time.Time, maxAge time.Duration, secret string) error {
	if strings.TrimSpace(secret) == "" {
		return errors.New("agent internal signing secret must not be empty")
	}
	if maxAge <= 0 {
		return errors.New("agent signature max age must be positive")
	}
	if !strings.HasPrefix(headers.Signature, signaturePrefix) {
		return errors.New("invalid agent signature")
	}

	seconds, err := strconv.ParseInt(headers.Timestamp, 10, 64)
	if err != nil {
		return errors.New("invalid agent signature")
	}
	timestamp := time.Unix(seconds, 0)
	if timestamp.After(now.Add(maxAge)) || now.Sub(timestamp) > maxAge {
		return errors.New("agent signature has expired")
	}

	expected, err := SignRequest(method, path, body, timestamp, secret)
	if err != nil || !hmac.Equal([]byte(expected.Signature), []byte(headers.Signature)) {
		return errors.New("invalid agent signature")
	}
	return nil
}

func canonicalRequest(method, path, timestamp string, body []byte) []byte {
	prefix := strings.Join(
		[]string{signatureVersion, strings.ToUpper(strings.TrimSpace(method)), path, timestamp, ""},
		"\n",
	)
	return append([]byte(prefix), body...)
}
